[build]
  publish = "public"
  command = "yarn osuny build"

[build.environment]
  HUGO_VERSION = "0.159.2"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/equipe/louann-pigearias/"
  to = "/equipe/lou-ann-pigearias/"

[[redirects]]
  from = "/mentions-legales/"
  to = "/legal/"

[[redirects]]
  from = "/equipe/louann-pigearias/actualites/"
  to = "/equipe/louann-pigearias/series/"

[[redirects]]
  from = "/actualites/"
  to = "/series/"

